<a href="https://colab.research.google.com/github/yshungria-uniandes/Data-Science-and-ML/blob/main/02-numpy/02.1-Intro-to-Numpy.es.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Logo de NumPy](https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/assets/numpy_logo.png?raw=true)

## Introducción a NumPy

`NumPy` es un juego de palabras que significa **Python numérico** (*Numerical Python*). Es una librería de código abierto que se utiliza para llevar a cabo tareas matemáticas con altísima eficiencia. Además, introduce estructuras de datos como los arrays multidimensionales, que se pueden operar entre ellos a alto nivel, sin meterse mucho en el detalle.

En concreto, las claves de esta librería son:

- **Array multidimensionales**: Esta librería proporciona un objeto llamado `ndarray`, que permite almacenar y manipular grandes conjuntos de datos de forma eficiente. Los arrays pueden tener cualquier número de dimensiones.
- **Operaciones Vectorizadas**: NumPy permite realizar operaciones matemáticas en arrays completos sin la necesidad de bucles explícitos en el código, lo que lo hace muy rápido y eficiente.
- **Funciones matemáticas**: NumPy proporciona una amplia gama de funciones matemáticas para trabajar con arrays, incluyendo funciones trigonométricas, estadísticas, álgebra lineal, entre otras.
- **Eficiencia**: Es mucho más rápido que la misma funcionalidad implementada directamente sobre Python nativo. Además, es muy flexible en términos de acceso y manipulación de elementos individuales o subconjuntos de arrays.

NumPy es una biblioteca fundamental para el Machine Learning y la ciencia de los datos en Python. Proporciona una amplia gama de herramientas y funciones para trabajar eficientemente con datos numéricos en forma de arrays y matrices.

### Arrays

Un **array** de NumPy es una estructura de datos que permite almacenar una colección de elementos, generalmente números, en una o más dimensiones.

#### Array unidimensional

Un array unidimensional (1D) de NumPy es una estructura de datos que contiene una secuencia de elementos en una única dimensión. Es similar a una lista en Python, pero con las ventajas de rendimiento y funcionalidad que ofrece NumPy.

![Array de una dimensión](https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/assets/1D.png?raw=true "1D")

Un array 1D puede ser creado usando la función `array` de la librería con una lista de elementos como argumento. Por ejemplo:

In [1]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

Esto creará un array 1D con los elementos 1, 2, 3, 4 y 5. Los elementos del array deben ser del mismo tipo de datos. Si los elementos son de diferentes tipos, NumPy intentará convertirlos al mismo tipo si es posible.

En un array 1D, podemos acceder a los elementos usando **índices** (*indexes*), modificarlos y realizar operaciones matemáticas en el array completo de forma eficiente. A continuación se muestran algunas operaciones que se pueden realizar utilizando el array anterior:

In [2]:
# Acceder al tercer elemento
print(array[2])

# Cambiar el valor del segundo elemento
array[1] = 7
print(array)

# Sumar 10 a todos los elementos
array += 10
print(array)

# Calcular la suma de los elementos
sum_all = np.sum(array)
print(sum_all)

3
[1 7 3 4 5]
[11 17 13 14 15]
70


#### Array N-dimensional

Un array multidimensional o n-dimensional en NumPy es una estructura de datos que organiza elementos en múltiples dimensiones (ejes). Estos arrays permiten representar estructuras de datos más complejas, como matrices (array 2D, 2 ejes), tensores (array 3D, 3 ejes) y estructuras de mayor dimensión.

![Arrays de diferentes dimensiones](https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/assets/3D.png?raw=true "3D")

Un array N-dimensional puede ser creado también usando la función `array` de la librería. Por ejemplo, si queremos crear un array 2D:

In [3]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Si ahora quisiéramos crear un array 3D, tendríamos que pensar en él como una lista de matrices:

In [4]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Al igual que sucedía con los arrays 1D, los elementos en un array multidimensional son accesibles mediante índices, se pueden realizar operaciones con ellos, etcétera.

A medida que agregamos más dimensiones, el principio básico sigue siendo el mismo: cada dimensión adicional puede considerarse como un nivel adicional de anidamiento. Sin embargo, a nivel práctico, trabajar con arrays de más de 3 o 4 dimensiones puede volverse más complejo y menos intuitivo.

Los arrays n-dimensionales en NumPy permiten una gran flexibilidad y potencia para representar y manipular datos en formas más complejas, especialmente útiles en campos como la ciencia de los datos, procesamiento de imágenes y aprendizaje profundo.

### Funciones

NumPy proporciona una gran cantidad de funciones predefinidas y que se pueden aplicar directamente sobre las estructuras de datos vistas anteriormente o las propias de Python (listas, matrices, etcétera). Algunas de las más utilizadas en el análisis de datos son:

In [5]:
import numpy as np

# Crear un array para el ejemplo
arr = np.array([1, 2, 3, 4, 5])

# Operaciones Aritméticas
print("Suma:", np.add(arr, 5))
print("Producto:", np.multiply(arr, 3))

# Logarítmicas y Exponenciales
print("Logaritmo natural:", np.log(arr))
print("Exponencial:", np.exp(arr))

# Funciones Estadísticas
print("Media:", np.mean(arr))
print("Mediana:", np.median(arr))
print("Desviación estándar:", np.std(arr))
print("Varianza:", np.var(arr))
print("Máximo valor:", np.max(arr))
print("Índice del máximo valor:", np.argmax(arr))
print("Mínimo valor:", np.min(arr))
print("Índice del mínimo valor:", np.argmin(arr))
print("Suma de todos los elementos:", np.sum(arr))

# Funciones de Redondeo
arr_decimal = np.array([1.23, 2.47, 3.56, 4.89])
print("Redondeo:", np.around(arr_decimal))
print("Entero menor (floor):", np.floor(arr_decimal))
print("Entero mayor (ceil):", np.ceil(arr_decimal))

Suma: [ 6  7  8  9 10]
Producto: [ 3  6  9 12 15]
Logaritmo natural: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Exponencial: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Media: 3.0
Mediana: 3.0
Desviación estándar: 1.4142135623730951
Varianza: 2.0
Máximo valor: 5
Índice del máximo valor: 4
Mínimo valor: 1
Índice del mínimo valor: 0
Suma de todos los elementos: 15
Redondeo: [1. 2. 4. 5.]
Entero menor (floor): [1. 2. 3. 4.]
Entero mayor (ceil): [2. 3. 4. 5.]


## Ejercicios: Haz clic en "open in colab" para realizarlos

> Solución: https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/02.1-Intro-to-Numpy_solutions.ipynb

### Creación de arrays

#### Ejercicio 01:  Crea un **vector nulo** (*null vector*) que tenga 10 elementos (★☆☆)

Un vector nulo es un array de una dimensión compuesto por ceros (`0`).

> NOTA: Revisa la función `np.zeros` (https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Ejercicio 02: Crea un vector de unos que tenga 10 elementos (★☆☆)

> NOTA: Revisa la función `np.ones` (https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Ejercicio 03: Investiga la función `linspace` de NumPy y crea un array que contenga 10 elementos (★☆☆)

> NOTA: Revisa la función `np.linspace` (https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [8]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#### Ejercicio 04: Busca varias formas de generar un array con números aleatorios y crea un array 1D y dos arrays 2D (★★☆)

> NOTA: Revisa las funciones `np.random.rand` (https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html), `np.random.randint` (https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html) y `np.random.randn` (https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html)

In [18]:
'''
La función np.random.rand() es una función de la biblioteca NumPy de Python que genera un número aleatorio a partir de una distribución uniforme continua entre 0 y 1.

Cuando se llama a la función np.random.rand(), esta genera un número aleatorio entre 0 y 1, donde todos los valores dentro de este rango tienen la misma probabilidad de ser generados. Este número aleatorio puede ser utilizado en diversas aplicaciones, como la generación de datos aleatorios para pruebas estadísticas, la simulación de procesos estocásticos, entre otros.

Es importante tener en cuenta que la función np.random.rand() genera un número aleatorio diferente cada vez que se llama, por lo que si se desea generar una secuencia de números aleatorios a partir de una distribución uniforme continua entre 0 y 1, se debe llamar a la función varias veces o utilizar otras funciones de la biblioteca NumPy que permitan generar una secuencia de números aleatorios a partir de esta distribución.

Además, la función np.random.rand() no requiere de ningún argumento de entrada y siempre genera un número aleatorio con un valor decimal entre 0 y 1.
'''
np.random.rand(3, 2)

array([[0.33490987, 0.04782556],
       [0.71429949, 0.78216178],
       [0.67646401, 0.74618436]])

In [32]:
'''
La función np.random.randint de la biblioteca NumPy de Python genera un arreglo de números enteros aleatorios entre dos valores especificados.

La sintaxis de la función np.random.randint es la siguiente:

np.random.randint(low, high=None, size=None, dtype=int)
'''
random_number =np.random.randint(1, 10)
random_number

#Generate a 2 x 4 array of ints between 0 and 4, inclusive:
np.random.randint(5, size=(2, 4))

array([[3, 2, 2, 0],
       [0, 0, 4, 1]])

In [23]:
'''
La función np.random.randn() es una función de la biblioteca NumPy de Python que genera un número aleatorio a partir de una distribución normal estándar, también conocida como distribución gaussiana.
Cuando se llama a la función np.random.randn(), esta genera un número aleatorio a partir de la distribución normal estándar, con una media de cero y una desviación estándar de uno. Este número aleatorio puede ser utilizado en diversas aplicaciones, como la generación de datos aleatorios para pruebas estadísticas, la simulación de procesos estocásticos, entre otros.
'''
matriz = np.random.randn(2, 4)
print(matriz)
desviacion_estandar = np.std(matriz)

print(desviacion_estandar)


[[-0.90484449  0.80593589 -1.1590064  -2.2548755 ]
 [-0.29397742  0.1582738   0.46416648  0.16008977]]
0.9424261432547673


#### Ejercicio 05: Crea una matriz (array 2D) identidad de 5x5 (★☆☆)


> NOTA: Revisa la función `np.eye`(https://numpy.org/devdocs/reference/generated/numpy.eye.html)

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Ejercicio 06: Crea una matriz con números aleatorios de 3x2 y calcula el valor mínimo y máximo (★☆☆)

> NOTA: Revisa la función `np.min` (https://numpy.org/devdocs/reference/generated/numpy.min.html) y `np.max` (https://numpy.org/devdocs/reference/generated/numpy.max.html)

In [ ]:
import numpy as np

# Creamos una matriz de 3x2 con números aleatorios entre 0 y 10
matriz = np.random.randint(10, size=(3, 2))

# Calculamos el valor mínimo y máximo de la matriz
minimo = np.min(matriz)
maximo = np.max(matriz)

# Mostramos la matriz y los valores mínimo y máximo
print("Matriz:")
print(matriz)
print("Valor mínimo:", minimo)
print("Valor máximo:", maximo)

#### Ejercicio 07: Crea un vector con números aleatorios de 30 elementos y calcula la media (★☆☆)

> NOTA: Revisa la función `np.mean` (https://numpy.org/doc/stable/reference/generated/numpy.mean.html)

In [39]:
# import numpy as np

# Creamos un vector de 30 elementos con números aleatorios entre 0 y 1
vector = np.random.rand(30)

# Calculamos la media del vector
# La media es una medida estadística que representa el valor promedio de un conjunto de datos. También se conoce como promedio o media aritmética.
media = np.mean(vector)

# Mostramos el vector y la media
print("Vector:")
print(vector)
print("Media:", media)

Vector:
[0.73568833 0.69030798 0.63156242 0.07950915 0.73659375 0.25466859
 0.8720968  0.16010559 0.11613946 0.23430275 0.44825447 0.14558795
 0.62055891 0.85752564 0.28311184 0.74570225 0.46267085 0.00408298
 0.47567618 0.12521683 0.49683735 0.96053895 0.96477877 0.56753891
 0.47574442 0.84387245 0.18613942 0.35968276 0.12326197 0.54400415]
Media: 0.47339206193533007


#### Ejercicio 08: Convierte la lista `[1, 2, 3]` y la tupla `(1, 2, 3)` en arrays (★☆☆)

In [40]:
# Convertimos la lista en un array
lista = [1, 2, 3]
array_lista = np.array(lista)

# Convertimos la tupla en un array
tupla = (1, 2, 3)
array_tupla = np.array(tupla)

# Mostramos los arrays
print("Array de lista:", array_lista)
print("Array de tupla:", array_tupla)

Array de lista: [1 2 3]
Array de tupla: [1 2 3]


### Operaciones entre arrays

#### Ejercicio 09: Invierte el vector del ejercicio anterior (★☆☆)

> NOTA: Revisa la función `np.flip` (https://numpy.org/doc/stable/reference/generated/numpy.flip.html)

In [41]:
tupla = (1, 2, 3)
array_tupla = np.array(tupla)
np.flip(array_tupla )

array([3, 2, 1])

#### Ejercicio 10: Cambia el tamaño de un array aleatorio de dimensiones 5x12 en 12x5 (★☆☆)

> NOTA: Revisa la función `np.reshape` (https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

In [42]:
#import numpy as np

# Creamos un array aleatorio de dimensiones 5x12
array_5x12 = np.random.rand(5, 12)

# Cambiamos el tamaño del array a 12x5
array_12x5 = np.reshape(array_5x12, (12, 5))

# Mostramos los arrays
print("Array original 5x12:")
print(array_5x12)
print("\nArray nuevo 12x5:")
print(array_12x5)

Array original 5x12:
[[0.56014543 0.25233509 0.72103638 0.75938168 0.39954436 0.44022191
  0.29005737 0.95188352 0.07359563 0.72654283 0.2476205  0.86372694]
 [0.08566877 0.33364915 0.73814784 0.36232924 0.07026539 0.69984769
  0.29309671 0.10776046 0.65018184 0.96501023 0.47436069 0.11964662]
 [0.59248197 0.42305405 0.72836197 0.58966095 0.82482323 0.45155765
  0.30059911 0.34384115 0.56905687 0.53803665 0.39093044 0.01461734]
 [0.7763945  0.44948782 0.21694139 0.4306     0.80280204 0.41078323
  0.45097654 0.99882196 0.33385661 0.97023292 0.61884506 0.90897316]
 [0.19628013 0.18011215 0.51676208 0.47723578 0.86386099 0.1142222
  0.91025545 0.9195585  0.94758936 0.04331003 0.63061789 0.58863495]]

Array nuevo 12x5:
[[0.56014543 0.25233509 0.72103638 0.75938168 0.39954436]
 [0.44022191 0.29005737 0.95188352 0.07359563 0.72654283]
 [0.2476205  0.86372694 0.08566877 0.33364915 0.73814784]
 [0.36232924 0.07026539 0.69984769 0.29309671 0.10776046]
 [0.65018184 0.96501023 0.47436069 0.119646

#### Ejercicio 11: Convierte la lista `[1, 2, 0, 0, 4, 0]` en un array y obtén el índice de los elementos que no son cero (★★☆)

> NOTA: Revisa la función `np.where` (https://numpy.org/devdocs/reference/generated/numpy.where.html)

In [45]:
#import numpy as np

# Convertimos la lista en un array
lista = [1, 2, 0, 0, 4, 0]
array = np.array(lista)

# Obtenemos los índices de los elementos que no son cero
indices = np.where(array != 0)

# Mostramos los índices
print("Índices de los elementos que no son cero:", indices[0])


Índices de los elementos que no son cero: [0 1 4]


#### Ejercicio 12: Convierte la lista `[0, 5, -1, 3, 15]` en un array, multiplica sus valores por `-2` y obtén los elementos pares (★★☆)

In [46]:
#import numpy as np

# Convertimos la lista en un array
lista = [0, 5, -1, 3, 15]
array = np.array(lista)

# Multiplicamos los valores del array por -2
array = array * -2

# Obtenemos los índices de los elementos pares
indices_pares = np.where(array % 2 == 0)

# Extraemos los elementos pares del array
elementos_pares = array[indices_pares]

# Mostramos los elementos pares
print("Elementos pares:", elementos_pares)

Elementos pares: [  0 -10   2  -6 -30]


#### Ejercicio 13: Crea un vector aleatorio de 10 elementos y ordénalo de menor a mayor (★★☆)

> NOTA: Revisa la función `np.sort` (https://numpy.org/doc/stable/reference/generated/numpy.sort.html)

In [47]:
#import numpy as np

# Creamos un vector aleatorio de 10 elementos
vector = np.random.rand(10)

# Ordenamos el vector de menor a mayor
vector_ordenado = np.sort(vector)

# Mostramos el vector ordenado
print("Vector ordenado:", vector_ordenado)

Vector ordenado: [0.00488892 0.29616144 0.35773269 0.37563678 0.49364698 0.65131983
 0.6993653  0.77629984 0.8381864  0.9164491 ]


#### Ejercicio 14: Genera dos vectores aleatorios de 8 elementos y aplica las operaciones de suma, resta y multiplicación entre ellos (★★☆)

> NOTA: Revisa las funciones matemáticas: https://numpy.org/doc/stable/reference/routines.math.html

In [49]:
#import numpy as np

# Creamos dos vectores aleatorios de 8 elementos
vector1 = np.random.rand(8)
vector2 = np.random.rand(8)

# Aplicamos las operaciones de suma, resta y multiplicación elemento a elemento
suma = vector1 + vector2
resta = vector1 - vector2
multiplicacion = vector1 * vector2

# Mostramos los resultados
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Suma:", suma)
print("Resta:", resta)
print("Multiplicación:", multiplicacion)

Vector 1: [0.54613704 0.87947877 0.45346902 0.63661461 0.28569872 0.04937928
 0.41764492 0.88407544]
Vector 2: [0.06737265 0.57459917 0.7151811  0.06131804 0.02777632 0.40085444
 0.9018194  0.37330182]
Suma: [0.61350969 1.45407794 1.16865013 0.69793266 0.31347504 0.45023372
 1.31946431 1.25737726]
Resta: [ 0.4787644   0.3048796  -0.26171208  0.57529657  0.2579224  -0.35147516
 -0.48417448  0.51077362]
Multiplicación: [0.0367947  0.50534777 0.32431247 0.03903596 0.00793566 0.0197939
 0.37664029 0.33002697]


#### Ejercicio 15: Convierte la lista `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]` en un array y transfórmalo en una matriz con filas de 3 columnas (★★★)

In [50]:
#import numpy as np

# Convertimos la lista en un array
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
array = np.array(lista)

# Transformamos el array en una matriz con filas de 3 columnas
matriz = np.reshape(array, (4, 3))

# Mostramos la matriz
print("Matriz:", matriz)

Matriz: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
